### ISSUE TITLE
Error while installing npm (db-nuodb) for node.js

### ISSUE THREAD

**Issue by PradeepRajK** [nuodb/node-db-nuodb#23]
Error while installing npm (db-nuodb) for node.js

Hi All,

i am getting error while installing the npm package manager(i.e db-nuodb) for my ubuntu machine, the error message is

npm http GET http://registry.npmjs.org/db-nuodb
npm http 304 http://registry.npmjs.org/db-nuodb

> db-nuodb@2.0.2 install /usr/local/lib/node_modules/db-nuodb
> make build && make install

# configure and build npm module
node-gyp configure
node-gyp build
make[1]: Entering directory `/usr/local/lib/node_modules/db-nuodb/build'
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/binding.o
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/connection.o
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/events.o
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/exception.o
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/query.o
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/result.o
  CXX(target) Release/obj.target/nuodb_bindings/src/node_db_nuodb_bindings.o
  CXX(target) Release/obj.target/nuodb_bindings/src/node_db_nuodb.o
In file included from ../src/node_db_nuodb.cc:30:0:
../src/./node_db_nuodb_connection.h:34:24: fatal error: Connection.h: No such file or directory
compilation terminated.
make[1]: *** [Release/obj.target/nuodb_bindings/src/node_db_nuodb.o] Error 1
make[1]: Leaving directory `/usr/local/lib/node_modules/db-nuodb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.0-29-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /usr/local/lib/node_modules/db-nuodb
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok
make: *** [build] Error 1

> db-nuodb@2.0.2 uninstall /usr/local/lib/node_modules/db-nuodb
> make clean

# remove module dependencies
node-gyp clean
rm -rf build
npm ERR! db-nuodb@2.0.2 install: `make build && make install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the db-nuodb@2.0.2 install script.
npm ERR! This is most likely a problem with the db-nuodb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build && make install
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-nuodb
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "db-nuodb"
npm ERR! cwd /home/ide
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ide/npm-debug.log
npm ERR! not ok code 0

Thanks in advance,
Pradeep Raj.K

**Comment by PradeepRajK** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5382626/9762825/825428ae-5723-11e5-9964-b7c113e30748.png)
oouhhfoiidshglkhfdglkfdhnglkdfhglkdfhglkfdh
likhslkfghfdlkjghdfoijghdiouf

**Comment by PradeepRajK** [comment]
![desert](https://cloud.githubusercontent.com/assets/5382626/9763026/e22aff7c-5724-11e5-83a6-5bf33f1a1873.jpg)
![chrysanthemum](https://cloud.githubusercontent.com/assets/5382626/9763027/e25787ea-5724-11e5-851f-3abf51174e04.jpg)
![penguins](https://cloud.githubusercontent.com/assets/5382626/9763029/e3ca5cba-5724-11e5-9980-531284868862.jpg)

**Comment by PradeepRajK** [comment]
![tulips](https://cloud.githubusercontent.com/assets/5382626/9808804/4736c962-5880-11e5-91ed-cc9df6aa9419.jpg)

**Comment by VDuda** [comment]
Hello PradeepRajK!

We require that you have NuoDB on your system before hand. When you install the db-nuodb package part of the make process still relies on libraries from the nuodb package. You should get the latest version of nuodb (http://download.nuodb.com) before trying to install the npm package. If you already have NuoDB, but not in the default /opt/nuodb directory, you can also explicitly state the location of your NuoDB install using the NUODB_HOME environment variable.
